version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_KEY=base64:qDJI4rbUY3ohN2ec2UQLU5RwHd+EPbHL7SJaKKh399U=
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    ports:
      - "9000:9000"
    depends_on:
      - db
    command: ["/usr/local/bin/wait-for-db.sh", "db", "php-fpm"]

  db:
    image: postgres:14
    container_name: laravel_db
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  postgres_data: